
global:
  # Image registry (and optional repository sub path) to use for all images
  imageRegistryPrefix: "127.0.0.1:30000"

image:
  pullPolicy: Always
  tag: "latest"

frontend:
  image:
    image: "emoji-chat/frontend"

backend:
  image:
    image: "emoji-chat/backend"
  llmServerUrl: "http://llm-server:11434"

backendLlm:
  image:
    image: "emoji-chat/backend-llm"

ingress:
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - "" # Wildcard host (default host rule)
  # tls:
  #   - secretName: "emoji-chat-tls"
  #     hosts:
  #       - "emoji-chat.moshicon.se"
