
global:
  # Image registry (and optional repository sub path) to use for all images
  imageRegistryPrefix: "127.0.0.1:30000/emojo-chat"

image:
  pullPolicy: Always
  tag: "latest"

frontend:
  image:
    image: "frontend"

backend:
  image:
    image: "backend"
  llmServerUrl: "http://llm-server:11434"

backendLlm:
  image:
    image: "llm"

ingress:
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - "" # Wildcard host (default host rule)
  tls:
    - hosts: []
      #  - "emojo-chat.moshicon.se"
      # secretName: "emojo-chat-tls"
